name: glow_routine
description: Skincare & haircare routine tracker demo (freezed/json, cached images, intl, go_router, secure storage)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^17.1.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_secure_storage: ^10.0.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true